name: 'master'

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Docker Login
      run: docker login -u soletan -p $DOCKER_HUB_TOKEN
      env:
        DOCKER_HUB_TOKEN: ${{ secrets.DOCKER_HUB_TOKEN }}
    - name: Docker Build
      run: docker build --tag cepharum/smtp:latest .
    - name: Docker Publish
      run: docker push cepharum/smtp:latest

